<a href="https://colab.research.google.com/github/hoanbklucky/Kinematics-and-Control-of-Robots/blob/main/compute_the_forward_kinematics_RPR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from sympy import Symbol, cos as c, sin as s, pi

In [3]:
def transformation_matrix(alpha, a, d, theta):
    T = np.array([[c(theta),              -s(theta),             0,                             a],
                     [s(theta)*c(alpha),     c(theta)*c(alpha),    -s(alpha),             -s(alpha)*d],
                     [s(theta)*s(alpha),  c(theta)*s(alpha),        c(alpha),              c(alpha)*d],
                     [0,                         0,                  0,                             1]
                     ])
    return T

In [4]:
theta1 = Symbol('theta1')
theta3 = Symbol('theta3')
d2 = Symbol('d2')
L2 = Symbol('L2')

In [5]:
dh = np.array([[0, 0, 0, theta1],
              [pi/2, 0, d2, 0],
               [0, 0, L2, theta3]])
print(dh)

[[0 0 0 theta1]
 [pi/2 0 d2 0]
 [0 0 L2 theta3]]


In [10]:
# {1} relative to {0}
T01 = transformation_matrix(dh[0][0], dh[0][1], dh[0][2], dh[0][3])

print(T01)

[[cos(theta1) -sin(theta1) 0 0]
 [sin(theta1) cos(theta1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [11]:
# {2} relative to {1}
T12 = transformation_matrix(dh[1][0], dh[1][1], dh[1][2], dh[1][3])

print(T12)

[[1 0 0 0]
 [0 0 -1 -d2]
 [0 1 0 0]
 [0 0 0 1]]


In [12]:
# {3} relative to {2}
T23 = transformation_matrix(dh[2][0], dh[2][1], dh[2][2], dh[2][3])

print(T23)

[[cos(theta3) -sin(theta3) 0 0]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 1 L2]
 [0 0 0 1]]


In [14]:
# {31} relative to {1}
T13 = np.matmul(T12, T23)

print(T13)

[[cos(theta3) -sin(theta3) 0 0]
 [0 0 -1 -L2 - d2]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 0 1]]


In [15]:
# {3} relative to {0}
T03 = np.matmul(T01, T13)

print(T03)

[[cos(theta1)*cos(theta3) -sin(theta3)*cos(theta1) sin(theta1)
  -(-L2 - d2)*sin(theta1)]
 [sin(theta1)*cos(theta3) -sin(theta1)*sin(theta3) -cos(theta1)
  (-L2 - d2)*cos(theta1)]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 0 1]]
