<a href="https://colab.research.google.com/github/hoanbklucky/Kinematics-and-Control-of-Robots/blob/main/Compute_the_Forward_Kinematics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from sympy import Symbol, cos as c, sin as s

In [ ]:
theta1 = Symbol('theta1')
d2 = Symbol('d2')
L2 = Symbol ('L2')
theta3 = Symbol('theta3')

In [ ]:
dh = np.array([[0, 0, 0, theta1], [np.pi/2, 0, d2, 0], [0, 0, L2, theta3]])
print(dh)

[[0 0 0 theta1]
 [1.5707963267948966 0 d2 0]
 [0 0 L2 theta3]]


In [ ]:
T1_0 = np.array([[c(dh[0][3]),              -s(dh[0][3]),             0,                             dh[0][1]],
        [s(dh[0][3])*c(dh[0][0]),  c(dh[0][3])*c(dh[0][0]),  -s(dh[0][0]),     -s(dh[0][0])*dh[0][2]],
        [s(dh[0][3])*s(dh[0][0]),  c(dh[0][3])*s(dh[0][0]),  c(dh[0][0]),       c(dh[0][0])*dh[0][2]],
        [0,                             0,                             0,                             1]])

print(T1_0)

[[cos(theta1) -sin(theta1) 0 0]
 [sin(theta1) cos(theta1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
T2_1 = np.array([[c(dh[1][3]),              -s(dh[1][3]),             0,                             dh[1][1]],
        [s(dh[1][3])*c(dh[1][0]),  c(dh[1][3])*c(dh[1][0]),  -s(dh[1][0]),     -s(dh[1][0])*dh[1][2]],
        [s(dh[1][3])*s(dh[1][0]),  c(dh[1][3])*s(dh[1][0]),  c(dh[1][0]),       c(dh[1][0])*dh[1][2]],
        [0,                             0,                             0,                             1]])

print(T2_1)

[[1 0 0 0]
 [0 6.12323399573677e-17 -1.00000000000000 -1.0*d2]
 [0 1.00000000000000 6.12323399573677e-17 6.12323399573677e-17*d2]
 [0 0 0 1]]


In [ ]:
T3_2 = np.array([[c(dh[2][3]),              -s(dh[2][3]),             0,                             dh[2][1]],
        [s(dh[2][3])*c(dh[2][0]),  c(dh[2][3])*c(dh[2][0]),  -s(dh[2][0]),     -s(dh[2][0])*dh[2][2]],
        [s(dh[2][3])*s(dh[2][0]),  c(dh[2][3])*s(dh[2][0]),  c(dh[2][0]),       c(dh[2][0])*dh[2][2]],
        [0,                             0,                             0,                             1]])

print(T3_2)

[[cos(theta3) -sin(theta3) 0 0]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 1 L2]
 [0 0 0 1]]


In [ ]:
for i, parameters in enumerate(dh):
    alpha = parameters[0]
    a = parameters[1]
    d = parameters[2]
    theta = parameters[3]
    print(f"index: {i}, alpha: {alpha}, a: {a}, d: {d}, theta: {theta}")
    T = np.array([[c(theta),              -s(theta),             0,                             a],
                     [s(theta)*c(alpha),     c(theta)*c(alpha),    -s(alpha),             -s(alpha)*d],
                     [s(theta)*s(alpha),  c(theta)*s(alpha),        c(alpha),              c(alpha)*d],
                     [0,                         0,                  0,                             1]
                     ])
    print(T)

index: 0, alpha: 0, a: 0, d: 0, theta: theta1
[[cos(theta1) -sin(theta1) 0 0]
 [sin(theta1) cos(theta1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]
index: 1, alpha: 1.5707963267948966, a: 0, d: d2, theta: 0
[[1 0 0 0]
 [0 6.12323399573677e-17 -1.00000000000000 -1.0*d2]
 [0 1.00000000000000 6.12323399573677e-17 6.12323399573677e-17*d2]
 [0 0 0 1]]
index: 2, alpha: 0, a: 0, d: L2, theta: theta3
[[cos(theta3) -sin(theta3) 0 0]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 1 L2]
 [0 0 0 1]]
