<a href="https://colab.research.google.com/github/hoanbklucky/Kinematics-and-Control-of-Robots/blob/main/Compute_the_Forward_Kinematics_PUMA_560.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
from sympy import Symbol, cos as c, sin as s, pi

In [3]:
def transformation_matrix(alpha, a, d, theta):
    T = np.array([[c(theta),              -s(theta),             0,                             a],
                     [s(theta)*c(alpha),     c(theta)*c(alpha),    -s(alpha),             -s(alpha)*d],
                     [s(theta)*s(alpha),  c(theta)*s(alpha),        c(alpha),              c(alpha)*d],
                     [0,                         0,                  0,                             1]
                     ])
    return T

In [4]:
theta1 = Symbol('theta1')
theta2 = Symbol('theta2')
theta3 = Symbol('theta3')
theta4 = Symbol('theta4')
theta5 = Symbol('theta5')
theta6 = Symbol('theta6')
a2 = Symbol('a2')
d3 = Symbol('d3')
a3 = Symbol('a3')
d4 = Symbol('d4')

In [8]:
dh = np.array([[0, 0, 0, theta1],
              [-pi/2, 0, 0, theta2],
               [0, a2, d3, theta3],
               [-pi/2, a3, d4, theta4],
               [pi/2, 0, 0, theta5],
               [-pi/2, 0, 0, theta6]])
print(dh)

[[0 0 0 theta1]
 [-pi/2 0 0 theta2]
 [0 a2 d3 theta3]
 [-pi/2 a3 d4 theta4]
 [pi/2 0 0 theta5]
 [-pi/2 0 0 theta6]]


In [9]:
T1_0 = transformation_matrix(dh[0][0], dh[0][1], dh[0][2], dh[0][3])

print(T1_0)

[[cos(theta1) -sin(theta1) 0 0]
 [sin(theta1) cos(theta1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [10]:
T2_1 = transformation_matrix(dh[1][0], dh[1][1], dh[1][2], dh[1][3])

print(T2_1)

[[cos(theta2) -sin(theta2) 0 0]
 [0 0 1 0]
 [-sin(theta2) -cos(theta2) 0 0]
 [0 0 0 1]]


In [11]:
T3_2 = transformation_matrix(dh[2][0], dh[2][1], dh[2][2], dh[2][3])

print(T3_2)

[[cos(theta3) -sin(theta3) 0 a2]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 1 d3]
 [0 0 0 1]]


In [12]:
T4_3 = transformation_matrix(dh[3][0], dh[3][1], dh[3][2], dh[3][3])

print(T4_3)

[[cos(theta4) -sin(theta4) 0 a3]
 [0 0 1 d4]
 [-sin(theta4) -cos(theta4) 0 0]
 [0 0 0 1]]


In [13]:
T5_4 = transformation_matrix(dh[4][0], dh[4][1], dh[4][2], dh[4][3])

print(T5_4)

[[cos(theta5) -sin(theta5) 0 0]
 [0 0 -1 0]
 [sin(theta5) cos(theta5) 0 0]
 [0 0 0 1]]


In [14]:
T6_5 = transformation_matrix(dh[5][0], dh[5][1], dh[5][2], dh[5][3])

print(T6_5)

[[cos(theta6) -sin(theta6) 0 0]
 [0 0 1 0]
 [-sin(theta6) -cos(theta6) 0 0]
 [0 0 0 1]]


In [24]:
T6_4 = np.matmul(T5_4, T6_5)

print(T6_4)

[[cos(theta5)*cos(theta6) -sin(theta6)*cos(theta5) -sin(theta5) 0]
 [sin(theta6) cos(theta6) 0 0]
 [sin(theta5)*cos(theta6) -sin(theta5)*sin(theta6) cos(theta5) 0]
 [0 0 0 1]]


In [25]:
T6_3 = np.matmul(T4_3, T6_4)

print(T6_3)

[[-sin(theta4)*sin(theta6) + cos(theta4)*cos(theta5)*cos(theta6)
  -sin(theta4)*cos(theta6) - sin(theta6)*cos(theta4)*cos(theta5)
  -sin(theta5)*cos(theta4) a3]
 [sin(theta5)*cos(theta6) -sin(theta5)*sin(theta6) cos(theta5) d4]
 [-sin(theta4)*cos(theta5)*cos(theta6) - sin(theta6)*cos(theta4)
  sin(theta4)*sin(theta6)*cos(theta5) - cos(theta4)*cos(theta6)
  sin(theta4)*sin(theta5) 0]
 [0 0 0 1]]


In [26]:
T3_1 = np.matmul(T2_1, T3_2)

print(T3_1)

[[-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3)
  -sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2) 0 a2*cos(theta2)]
 [0 0 1 d3]
 [-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2)
  sin(theta2)*sin(theta3) - cos(theta2)*cos(theta3) 0 -a2*sin(theta2)]
 [0 0 0 1]]


In [27]:
T6_1 = np.matmul(T3_1, T6_3)

print(T6_1)

[[(-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3))*(-sin(theta4)*sin(theta6) + cos(theta4)*cos(theta5)*cos(theta6)) + (-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))*sin(theta5)*cos(theta6)
  (-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3))*(-sin(theta4)*cos(theta6) - sin(theta6)*cos(theta4)*cos(theta5)) - (-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))*sin(theta5)*sin(theta6)
  -(-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3))*sin(theta5)*cos(theta4) + (-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))*cos(theta5)
  a2*cos(theta2) + a3*(-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3)) + d4*(-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))]
 [-sin(theta4)*cos(theta5)*cos(theta6) - sin(theta6)*cos(theta4)
  sin(theta4)*sin(theta6)*cos(theta5) - cos(theta4)*cos(theta6)
  sin(theta4)*sin(theta5) d3]
 [(sin(theta2)*sin(theta3) - cos(theta2)*cos(theta3))*sin(theta5)*cos(theta6) + (-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))*(-sin(theta4)*sin(theta6) + c

In [28]:
T6_0 = np.matmul(T1_0, T6_1)

print(T6_0)

[[((-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3))*(-sin(theta4)*sin(theta6) + cos(theta4)*cos(theta5)*cos(theta6)) + (-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))*sin(theta5)*cos(theta6))*cos(theta1) - (-sin(theta4)*cos(theta5)*cos(theta6) - sin(theta6)*cos(theta4))*sin(theta1)
  ((-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3))*(-sin(theta4)*cos(theta6) - sin(theta6)*cos(theta4)*cos(theta5)) - (-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))*sin(theta5)*sin(theta6))*cos(theta1) - (sin(theta4)*sin(theta6)*cos(theta5) - cos(theta4)*cos(theta6))*sin(theta1)
  (-(-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3))*sin(theta5)*cos(theta4) + (-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2))*cos(theta5))*cos(theta1) - sin(theta1)*sin(theta4)*sin(theta5)
  -d3*sin(theta1) + (a2*cos(theta2) + a3*(-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3)) + d4*(-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2)))*cos(theta1)]
 [((-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta

In [19]:
print(len(dh))

6


In [22]:
print(list(range(len(dh))))

[0, 1, 2, 3, 4, 5]


In [31]:
T3_1 = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])
for i in [1, 2]:
  T = transformation_matrix(dh[i][0], dh[i][1], dh[i][2], dh[i][3])
  T3_1 = np.matmul(T3_1, T)
print(T3_1)

[[-sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3)
  -sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2) 0 a2*cos(theta2)]
 [0 0 1 d3]
 [-sin(theta2)*cos(theta3) - sin(theta3)*cos(theta2)
  sin(theta2)*sin(theta3) - cos(theta2)*cos(theta3) 0 -a2*sin(theta2)]
 [0 0 0 1]]


In [33]:
T6_3 = np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]])
for i in [3, 4, 5]:
  T = transformation_matrix(dh[i][0], dh[i][1], dh[i][2], dh[i][3])
  T6_3 = np.matmul(T6_3, T)
print(T6_3)

[[-sin(theta4)*sin(theta6) + cos(theta4)*cos(theta5)*cos(theta6)
  -sin(theta4)*cos(theta6) - sin(theta6)*cos(theta4)*cos(theta5)
  -sin(theta5)*cos(theta4) a3]
 [sin(theta5)*cos(theta6) -sin(theta5)*sin(theta6) cos(theta5) d4]
 [-sin(theta4)*cos(theta5)*cos(theta6) - sin(theta6)*cos(theta4)
  sin(theta4)*sin(theta6)*cos(theta5) - cos(theta4)*cos(theta6)
  sin(theta4)*sin(theta5) 0]
 [0 0 0 1]]
